version: "3"
services:
  django:
    image: wfrp:test
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"
  next:
    image: wfrpfront
    # ports:
      # - "3000:3000"
    network_mode: "host"
    depends_on:
      - "django"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: obo69
      POSTGRES_DB: djangodb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 