version: "3"
services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile
    # ports:
    #   - "8000:8000"
    depends_on:
      - "postgres"
    volumes:
      - ./docker_media_root:/home/WFRP/media
  next:
    build:
      context: ./WFRP-Front
      dockerfile: Dockerfile
    # ports:
      # - "3000:3000"
    network_mode: "host"
    depends_on:
      - "django"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: obo69
      POSTGRES_DB: djangodb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
  nginx:
    build: ./nginx
    volumes:
      - ./docker_media_root:/home/WFRP/media
    ports:
      - 8000:80
    depends_on:
      - "django"