# Generated by Django 4.0.3 on 2022-03-15 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='Campaign',
            new_name='Master',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(default='Enter a description for your campaign'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
