# Generated by Django 4.0.3 on 2022-04-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='traits',
            field=models.ManyToManyField(blank=True, related_name='creature_traits', to='wfrp.creaturetrait'),
        ),
    ]
