# Generated by Django 4.0.3 on 2022-03-17 01:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name': 'journal entry', 'verbose_name_plural': 'journal entries'},
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
