# Generated by Django 4.0.3 on 2022-04-04 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wfrp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedskill',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='encumbrance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talent',
            name='times_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('consumable', 'consumable'), ('jewel', 'jewel'), ('trinket', 'trinket'), ('other', 'other')], max_length=32),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=32)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(blank=True, default='', max_length=32)),
                ('encumbrance', models.IntegerField(default=0)),
                ('weapon_range', models.CharField(blank=True, default='', max_length=32)),
                ('damage', models.CharField(blank=True, default='', max_length=32)),
                ('qualities', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to='wfrp.playablecharacter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'armor item',
                'verbose_name_plural': 'armour items',
            },
        ),
        migrations.CreateModel(
            name='Armour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=32)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('encumbrance', models.IntegerField(default=0)),
                ('armor_points', models.IntegerField(default=0)),
                ('locations', models.TextField(blank=True, default='')),
                ('qualities', models.TextField(blank=True, default='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armor_piece', to='wfrp.playablecharacter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armor_piece', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'armor item',
                'verbose_name_plural': 'armour items',
            },
        ),
    ]
