# Generated by Django 4.0.3 on 2022-03-31 14:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wfrp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playablecharacter',
            unique_together={('user', 'campaign')},
        ),
    ]
