# Generated by Django 4.0.3 on 2022-04-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0002_advancedskill_value_item_encumbrance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name': 'weapon', 'verbose_name_plural': 'weapons'},
        ),
        migrations.RenameField(
            model_name='spell',
            old_name='targets',
            new_name='target',
        ),
    ]
