# Generated by Django 4.0.3 on 2022-03-16 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wfrp', '0002_rename_campaign_campaign_master_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='Master',
        ),
        migrations.AddField(
            model_name='campaign',
            name='master',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
