# Generated by Django 4.0.3 on 2022-04-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0002_alter_playablecharacter_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
