# Generated by Django 4.0.3 on 2022-04-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0002_creature_is_default_creaturetrait_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='playablecharacter',
            name='melee',
            field=models.IntegerField(default=0),
        ),
    ]
