# Generated by Django 4.0.3 on 2022-04-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0003_alter_weapon_options_rename_targets_spell_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='playablecharacter',
            name='character_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
