# Generated by Django 4.0.3 on 2022-04-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0003_campaign_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playablecharacter',
            name='character_class',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
