# Generated by Django 4.0.3 on 2022-04-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0003_playablecharacter_melee'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_default',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
