# Generated by Django 4.0.3 on 2022-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0004_playablecharacter_character_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='playablecharacter',
            name='character_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
