# Generated by Django 4.0.3 on 2022-04-11 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0004_campaign_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
