# Generated by Django 4.0.3 on 2022-04-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0005_playablecharacter_character_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playablecharacter',
            old_name='current',
            new_name='current_experience',
        ),
        migrations.RenameField(
            model_name='playablecharacter',
            old_name='spent',
            new_name='spent_experience',
        ),
    ]
