# Generated by Django 4.0.3 on 2022-03-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0006_alter_playablecharacter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playablecharacter',
            name='character_class',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='playablecharacter',
            name='background_story',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='playablecharacter',
            name='long_term_ambitions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='playablecharacter',
            name='mutations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='playablecharacter',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='playablecharacter',
            name='personal_relations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='playablecharacter',
            name='psychology',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='playablecharacter',
            name='secrets',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='playablecharacter',
            name='short_term_ambitions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='spell',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='talent',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
