# Generated by Django 4.0.3 on 2022-04-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0006_alter_advancedskill_uuid_alter_armour_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='is_default',
        ),
    ]
