# Generated by Django 4.0.3 on 2022-04-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0006_rename_current_playablecharacter_current_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playablecharacter',
            name='motivation_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playablecharacter',
            name='motivation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
