# Generated by Django 4.0.3 on 2022-04-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0007_playablecharacter_motivation_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playablecharacter',
            name='max_wounds',
            field=models.IntegerField(default=0),
        ),
    ]
