# Generated by Django 4.0.3 on 2022-04-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0008_playablecharacter_max_wounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playablecharacter',
            name='career_path',
            field=models.TextField(blank=True, default=''),
        ),
    ]
