# Generated by Django 4.0.3 on 2022-04-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfrp', '0009_alter_playablecharacter_career_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='playablecharacter',
            name='heal',
            field=models.IntegerField(default=0),
        ),
    ]
